// leverageLimits.ts
// This file contains the hardcoded maximum leverage limits for each trading symbol.
// This is used as the single source of truth to prevent bots from requesting
// leverage amounts that would be rejected by the exchange.

export const leverageLimits = new Map<string, number>([
    ["INJUSDT", 25], ["EIGENUSDT", 2], ["ENSOUSDT", 5], ["ZORAUSDT", 5],
    ["SBETUSDT", 10], ["ARIAUSDT", 5], ["BANKUSDT", 5], ["ZRXUSDT", 25],
    ["OPBUSD", 25], ["EVAAUSDT", 5], ["WAVESUSDT", 25], ["TSLAUSDT", 10],
    ["STBLUSDT", 5], ["XTZUSDT", 75], ["BNBUSDT", 100], ["MONUSDT", 5],
    ["DARUSDT", 25], ["ETCUSDT", 50], ["XMRUSDT", 25], ["PENDLEUSDT", 25],
    ["CCUSDT", 5], ["RVVUSDT", 5], ["JANITORUSDT", 20], ["ALICEUSDT", 25],
    ["TOWNSUSDT", 5], ["BATUSDT", 50], ["DOGEUSDT", 25], ["1000BONKUSDT", 25],
    ["TRXUSDT", 25], ["SNXUSDT", 25], ["SAPIENUSDT", 5], ["EULUSDT", 5],
    ["EDENUSDT", 5], ["XLMUSDT", 25], ["DASHUSDT", 50], ["OKBUSDT", 25],
    ["KAVAUSDT", 25], ["SAHARAUSDT", 10], ["APEUSDT", 25], ["RUNEUSDT", 25],
    ["BNXUSDT", 25], ["OPUSDT", 25], ["SKLUSDT", 25], ["FOOTBALLUSDT", 20],
    ["CAKEBUSD", 25], ["OPENUSDT", 5], ["GDCBUSD", 20], ["RECALLUSDT", 5],
    ["MTLUSDT", 25], ["TOMOUSDT", 8], ["AFEEUSDT", 2], ["LTCUSDT", 25],
    ["FARTCOINUSDT", 50], ["BNBBUSD", 25], ["MANAUSDT", 25], ["TRBUSDT", 25],
    ["HEMIUSDT", 50], ["ONDOUSDT", 50], ["CUDISUSDT", 5], ["AVAXBUSD", 20],
    ["2ZUSDT", 5], ["GALUSDT", 25], ["PTBUSDT", 5], ["FORMUSDT", 5],
    ["OGNUSDT", 25], ["RNDRUSDT", 25], ["ENAUSDT", 50], ["AIAUSDT", 5],
    ["42USDT", 5], ["LUNAUSDT", 8], ["KNCUSDT", 25], ["ZRCUSDT", 5],
    ["ESPORTSUSDT", 5], ["ATOMUSDT", 25], ["SOLBUSD", 20], ["NMRUSDT", 25],
    ["SQDUSDT", 5], ["TRADOORUSDT", 5], ["ENSUSDT", 25], ["GASUSDT", 25],
    ["AGIXUSDT", 25], ["IOSTUSDT", 25], ["ZECUSDT", 5], ["HYPEUSDT", 300],
    ["FLOCKUSDT", 5], ["GALAUSDT", 25], ["EDUUSDT", 25], ["ALGOUSDT", 25],
    ["TAGUSDT", 5], ["MANTAUSDT", 25], ["LISTAUSDT", 5], ["METUSDT", 5],
    ["AAPLUSDT", 10], ["BTRUSDT", 5], ["LRCUSDT", 25], ["PYTHUSDT", 25],
    ["STXUSDT", 25], ["ARPAUSDT", 25], ["GIGGLEUSDT", 5], ["1INCHUSDT", 25],
    ["AIUSDT", 25], ["PIXELUSDT", 25], ["IOUSDT", 25], ["LINAUSDT", 25],
    ["TURTLEUSDT", 5], ["FILUSDT", 25], ["STRKUSDT", 25], ["NVDAUSDT", 10],
    ["TRUMPUSDT", 50], ["PUMPUSDT", 50], ["AIOUSDT", 5], ["SOLUSDT", 25],
    ["LOOMUSDT", 25], ["BLZUSDT", 25], ["BLASTUSDT", 25], ["GMTUSDT", 25],
    ["LOKAUSDT", 50], ["LINEAUSDT", 50], ["APTBUSD", 20], ["BANDUSDT", 25],
    ["LDOUSDT", 25], ["XRPBUSD", 25], ["PENGUUSDT", 50], ["XRPUSDT", 25],
    ["FTTUSDT", 20], ["4USDT", 5], ["BLUAIUSDT", 5], ["CRVUSDT", 25],
    ["BELUSDT", 25], ["METAUSDT", 10], ["DOTUSDT", 25], ["PROVEUSDT", 5],
    ["QQQUSDT", 10], ["TAKEUSDT", 5], ["APTUSDT", 25], ["USD1USDT", 25],
    ["SEIUSDT", 25], ["LENDUSDT", 50], ["AIBUSD", 20], ["FTMBUSD", 25],
    ["LINKBUSD", 25], ["MOODENGUSDT", 5], ["QTUMUSDT", 50], ["IOTAUSDT", 50],
    ["BTCBUSD", 25], ["XPINUSDT", 5], ["ADAUSDT", 25], ["TREEUSDT", 5],
    ["FFUSDT", 5], ["XNYUSDT", 5], ["HTUSDT", 25], ["BIGTIMEUSDT", 25],
    ["ETHUSDT", 100], ["ZKCUSDT", 5], ["LYNUSDT", 5], ["ORDIUSDT", 25],
    ["WOOUSDT", 25], ["SFPUSDT", 25], ["RLCUSDT", 25], ["GOOGUSDT", 10],
    ["CFXUSDT", 25], ["KGENUSDT", 5], ["MSFTUSDT", 10], ["GBPBUSD", 15],
    ["BUSDT", 5], ["AUDIOUSDT", 25], ["EURBUSD", 15], ["IDUSDT", 20],
    ["NEOUSDT", 50], ["SANDUSDT", 25], ["LINKUSDT", 25], ["MINAUSDT", 25],
    ["ONUSDT", 5], ["SPKUSDT", 5], ["RIFUSDT", 25], ["COAIUSDT", 5],
    ["ADABUSD", 25], ["INUSDT", 5], ["JASMYUSDT", 25], ["BASUSDT", 5],
    ["YGGUSDT", 25], ["DAMUSDT", 5], ["LUNA2USDT", 20], ["PORT3USDT", 5],
    ["ONTUSDT", 50], ["VETUSDT", 25], ["IMXUSDT", 25], ["NFPUSDT", 25],
    ["UBUSDT", 5], ["1000CHEEMSUSDT", 5], ["ARBUSDT", 25], ["GRTUSDT", 25],
    ["WLFIUSDT", 50], ["RIVERUSDT", 5], ["MITOUSDT", 5], ["AMZNUSDT", 10],
    ["MASKUSDT", 25], ["EOSUSDT", 25], ["SKYUSDT", 50], ["NBUSDT", 4],
    ["ZBTUSDT", 5], ["ZKUSDT", 25], ["SUIUSDT", 25], ["BARDUSDT", 5],
    ["1000BTTCUSDT", 50], ["COMMONUSDT", 5], ["MERLUSDT", 25], ["AVNTUSDT", 50],
    ["MATICBUSD", 20], ["CYBERUSDT", 25], ["C98USDT", 25], ["LABUSDT", 5],
    ["APRUSDT", 5], ["NEARUSDT", 25], ["KITEUSDT", 5], ["BCHUSDT", 25],
    ["YBUSDT", 5], ["LTCBUSD", 25], ["1000SHIBUSDT", 25], ["ETHWUSDT", 25],
    ["ETHBUSD", 25], ["CUSDT", 5], ["AAVEUSDT", 25], ["TONUSDT", 25],
    ["WIFUSDT", 50], ["MBLUSDT", 50], ["AVAXUSDT", 25], ["CAKEUSDT", 25],
    ["0GUSDT", 50], ["MATICUSDT", 25], ["MASKBUSD", 25], ["TIAUSDT", 25],
    ["MKRUSDT", 25], ["PEOPLEUSDT", 25], ["THETAUSDT", 50], ["UNIUSDT", 25],
    ["CLOUSDT", 5], ["PERPUSDT", 25], ["ARKMUSDT", 25], ["COMPUSDT", 25],
    ["ATUSDT", 4], ["BTCUSDT", 100], ["OMGUSDT", 50], ["1000PEPEUSDT", 25],
    ["FETUSDT", 25], ["1000FLOKIUSDT", 25], ["FTMUSDT", 25], ["DOGEBUSD", 20],
    ["QUSDT", 5], ["SXPUSDT", 25], ["WLDUSDT", 25], ["XEMUSDT", 25],
    ["HOLOUSDT", 5], ["ASTERUSDT", 50], ["BLESSUSDT", 5], ["1000LUNCBUSD", 25],
    ["ZILUSDT", 25], ["AXSUSDT", 25], ["DYDXUSDT", 25], ["OCEANUSDT", 25],
    ["TOSHIUSDT", 5], ["CHZUSDT", 25], ["CTSIUSDT", 25], ["XPLUSDT", 5],
    ["NEIROUSDT", 5]
]);